version: '3'

services:
  hdb:
    container_name: hdb
    build: ./ops/hdb
    ports:
      - 6543:5432
    networks:
      - rsl_network
    volumes:
      - hdb:/var/lib/postgresql/data
  hdb-api:
    container_name: hdb-api
    build: ./ops/hdb-api
    depends_on:
      - hdb
    networks:
      - rsl_network
    ports:
      - 85:8080
    volumes:
      # local:container
      - ./services/hdb-api:/usr/src/hdb_api

networks:
  rsl_network:

volumes:
  hdb:
