version: '3'

services:
  hdb:
    container_name: hdb
    build: ./ops/hdb
    ports:
      - 6543:5432
    networks:
      - rsl_network
    volumes:
      - hdb:/var/lib/postgresql/data
  hdb_crawler:
    container_name: hdb_crawler
    build: ops/hdb_crawler
    depends_on:
      - hdb
    networks:
      - rsl_network
    volumes:
      # local:container
      - ./hdb_crawler:/hdb_cralwer
      - hdb_data:/hdb_crawler/results
  hdb_api:
    container_name: hdb_api
    build: ops/hdb_api
    depends_on:
      - hdb
    networks:
      - rsl_network
#    volumes:
      # local:container
#      - ./hdb_api:/hdb_cralwer
#      - hdb_data:/hdb_crawler/results


networks:
  rsl_network:

volumes:
  hdb:
  hdb_data:
